### ISSUE TITLE
Support hostnetworking mode

### ISSUE THREAD

**Issue by clusc** [coreos/etcd-operator#1137]
we have a usage where we need to deploy metric collection agent(collectd) as daemonset on all nodes running etcd(one pod per node). The problem is the agent needs a stable way to talk to the etcd instance on the same node. By running both etcd and collectd under host networking mode, the metric agent can simply talk to `localhost:2379` to collect the metric. A reference implementation is in #1135.

**Comment by hongchaodeng** [comment]
When using hostNetwork, etcd members need anti-affinity across nodes. Otherwise there will be port conflict. I believe scheduler checks/guarantees that if container ports field is set. Just in case, it is still better to set anti-affinity.

But for your use case, I think it is better to run collectd along with etcd container in a pod, isn't it?

**Comment by clusc** [comment]
We want to separate deployment of etcd with collectd, so that if we decide to add/drop metrics it won't affect etcd deployment. And yes, for the hack build we have now, we set `antiAffinity: true`.

**Comment by xiang90** [comment]
> we have a usage where we need to deploy metric collection agent(collectd) as daemonset on all nodes running etcd(one pod per node).

I believe hostnet is overkill for this issue. A better way to resolve it is to make your metrics agent discovers etcd though another component (a proxy?).

**Comment by clusc** [comment]
@xiang90 I think it otherwise. We want to make sure collectd agents and etcd instances are 1-to-1 mapping, and on the same node, so that the `host` label exposed automatically by collectd would be correlate to the etcd host. Having another discover components to discover etcd hosts imho is an overkill, as we often use etcd as the discovery mechanism.

**Comment by xiang90** [comment]
@clusc 

Just to be clear, we (etcd operator) want to avoid enabling host networking if there is a workaround. It will cause us to many troubles.

When you run on k8s, you use k8s to do discovery not etcd. You need the "proxy" since `collected` does not understand k8s objects and cannot discover them. That has nothing to do with etcd.

**Comment by clusc** [comment]
I understand it has nothing to do with etcd, and more about kubernetes. Ideally if kubernetes could expose the other pods' info on the same vm through downward api then we can use that, but that's not available afaik. Having to go through any centralized discovery method(dns/service/k8s api) would create problem on the metrics collection agent since we need to differentiate etcd nodes and collectd is distributed by nature. HostNetwork is the simplest distributed discovery mechanism.

I am trying to understand what's the "troubles" you mentioned. It will be an optional parameter that will only be enabled if needed. What trouble will it bring to etcd-operator?

**Comment by xiang90** [comment]
@clusc 

Pod with host net and pod without host net behavior differently in quite a few cases due to the difference between Node IP vs VIP and Node network setup vs Pod network setup. It is not just a simple option to be turned on as you might think.

To support both, etcd operators add up complexity and tests matrixes. Moreover, it is not recommended to use host net in general. 

If there is a strong use case, we might support it (we already support hostnet for self hosted cluster). But your use case is not strong in my opinion.

**Comment by xiang90** [comment]
low activity. closing.
