### ISSUE TITLE
upgrade_test: pod deleted with zero grace period seems to remain for a bit more

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1204]
So in our test, we kill pod first and then wait for it to recover to given size.
The pod to kill was deleted with zero grace period. Our expectation is that it should be gone right away. However, it still remains for a bit more.
```
    	util.go:91: 2017-06-15 04:20:08.444585639 +0000 UTC backup pod (upgrade-test-v5tgx-backup-sidecar-431216634-vdms5) is running
    	util.go:91: 2017-06-15 04:20:34.067510096 +0000 UTC waiting size (3), healthy etcd members: names ([upgrade-test-v5tgx-0000 upgrade-test-v5tgx-0001 upgrade-test-v5tgx-0002])
    	upgrade_test.go:406: failed to get backup pod: pods "upgrade-test-v5tgx-0000" not found
```
This violates our assumptions.

**Comment by hasbro17** [comment]
Just wanted to comment that the above issue is caused because even if the pod is deleted right away, there is some delay before the TPR's ready members are updated. 
And since after #1101 we check the TPR for the cluster size and not the pods directly, it is possible that the test sees that the cluster has recovered when in fact the ready members are still the old pods are being terminated.

**Comment by hongchaodeng** [comment]
Good catch!

**Comment by hongchaodeng** [comment]
Is this fixed? @hasbro17

**Comment by hasbro17** [comment]
Yes, this should be fixed now that we're no longer getting the size from ready members. We'll know for sure after running the stress tests for a while.

**Comment by hasbro17** [comment]
The issue seems to be fixed. After #1208 this particular failure has not been seen in the last 30 runs of upgrade stress tests.
