### ISSUE TITLE
Support encryption of backup

### ISSUE THREAD

**Issue by klausenbusk** [coreos/etcd-operator#1308]
The etcd backup can contain some very sensitive data (e.g: when using self-hosted etcd with [bookube](https://github.com/coreos/bootkube), it contains all the k8s secrets).

The access to the backups should be restricted (ex: IAM), but providing a way to encrypt the backup wouldn't hurt.

**Comment by hongchaodeng** [comment]
@Nesze Moving discussion of https://github.com/coreos/etcd-operator/issues/1339 to here.

Encryption is preferable on etcd backup data. However, it shouldn't be coupled with etcd backup sidecar or etcd operator. etcd operator should only take the backup. It would then call another service to encrypt the data and even actually store the data into S3. Because this would make etcd operator have less dependencies and easier to maintain.

Solution:
- Ideally, we will have extensible storage backend design (https://github.com/coreos/etcd-operator/issues/1241) which calls REST APIs. If you can't wait for this, then
- Currently, we have a backend interface: https://github.com/coreos/etcd-operator/blob/2665c3e51963836119a296f37e10b71938c23c81/pkg/backup/backend.go . You can implement it, improve it to fit the use case.

**Comment by hongchaodeng** [comment]
Closing this.
See custom backup plan in https://github.com/coreos/etcd-operator/issues/1626
