### ISSUE TITLE
Unable to configure image used by backup sidecar

### ISSUE THREAD

**Issue by cbandy** [coreos/etcd-operator#1418]
We vendor the images we deploy to production and deploy only specific tags/versions. I noticed that even though the etcd-operator is deployed with our image, it creates a backup sidecar using `quay.io/coreos/etcd-operator`:

https://github.com/coreos/etcd-operator/blob/6a8e08ffc11cfc4dcd4f178ad1664cde16971bcb/pkg/util/k8sutil/backup.go#L110

I am able to work around this by updating the backup deployment _after_ a new cluster is deployed.

It would be nice if I could specify the image and tag/version somewhere in the cluster spec (or backup policy.)

**Comment by sitowitzp** [comment]
I am currently running into the same issue. I am able to configure internal registry hosted images for the etcd-operator and etcd BUT there does NOT seem to be a way to configure the sidecars and thus they all fail since Docker Hub is inaccessible from our corporate k8s environment. Any suggestions?

**Comment by hongchaodeng** [comment]
We have decoupled backup functionality from etcd operator.
Closing this issue since Sidecar is not in etcd operator anymore.
