### ISSUE TITLE
update milestone of open issues marked 0.6.1 to a future or 0.6.2

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd-operator#1590]
Noticed that v0.6.1 is released. Was expecting the issues marked with milestone to be fixed but doesn't seem like. 

Can they please be updated with a future milestone, say 0.6.2?
Also #1261

Was specifically looking for #1396, #1051(related to #1416) in the upcoming release, not sure about your priorities.

**Comment by hongchaodeng** [comment]
Sorry my fault. I put milestones but realized later we needed to work on something else due to company roadmap. We need to come up with a way to make this more public and better communicated.

> Can they please be updated with a future milestone, say 0.6.2?

We are releasing 0.7.0 for next. Need to decouple backup, restore spec.
With all those hard changes, we can minimize EtcdCluster's interfaces learnt from past lessons and move towards the stable roadmap.

> Was specifically looking for #1396, #1051(related to #1416) in the upcoming release, not sure about your priorities.

Yes. etcd auth, etcd version to 3.2, k8s version to 1.8 is on roadmap.
And please help with those issues :)

**Comment by raoofm** [comment]
>  I put milestones but realized later we needed to work on something else due to company roadmap. 

Sure it makes sense.

> We are releasing 0.7.0 for next. Need to decouple backup, restore spec.
With all those hard changes, we can minimize EtcdCluster's interfaces learnt from past lessons and move towards the stable roadmap

Perfect. Noticed those changes for the past few days via commits :+1: 

> Yes. etcd auth, etcd version to 3.2, k8s version to 1.8 is on roadmap.
And please help with those issues :)

Sure, excited as our cluster is 1.8 too

**Comment by hongchaodeng** [comment]
Closing this right now as all issues reported here are tracked in other issues and better converge discussion to them:

- etcd 3.2: https://github.com/coreos/etcd-operator/issues/1396, https://github.com/coreos/etcd-operator/pull/1607
- etcd auth: https://github.com/coreos/etcd-operator/issues/1051, https://github.com/coreos/etcd-operator/issues/1416
- k8s 1.8: https://github.com/coreos/etcd-operator/issues/1444
