### ISSUE TITLE
e2e master is failing: TestTLS

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1700]
https://jenkins-etcd.prod.coreos.systems/view/operator/job/etcd-operator-master/704/consoleText
```
--- FAIL: TestTLS (2.32s)
	tls_test.go:36: exit status 1
```

**Comment by hongchaodeng** [comment]
@fanminshi Can you take a look?

**Comment by fanminshi** [comment]
taking a look.

**Comment by fanminshi** [comment]
I run TestTLS locally and couldn't reproduce. I'll investigate more.

**Comment by hasbro17** [comment]
## How to reproduce
If you run the following tests in the same namespace in the following order then the issue arises.
1. e2e: `TestBackupAndRestore`
2. e2eslow: `TestTLS`

Run the tests with `PASSES=e2e e2eslow` and `E2E_TEST_SELECTOR=TLS|BackupAndRestore`

## Issue with tests
The first test `TestBackupAndRestore` creates the TLS secrets but doesn't remove them when the test is done.
https://github.com/coreos/etcd-operator/blob/master/test/e2e/backup_test.go#L65-L74

When the second test `TestTLS` is run it tries to create the TLS secrets as well.
https://github.com/coreos/etcd-operator/blob/master/test/e2e/e2eslow/tls_test.go#L28-L37
The problem is that the random suffix generated is the same because `rand.Unit64()` generates random values from the default source. So it ends up trying to create TLS secrets of the same name as the previous test. 

And so the `kubectl create secrets` command fails and returns exit 1.
https://github.com/coreos/etcd-operator/blob/master/test/e2e/e2eutil/tls.go#L63-L68

## Fix
The fix is to:
1. Seed rand correctly `rand.Seed(time.Now().UTC().UnixNano())`
2. Clean up the secrets in `TestBackupAndRestore`

Also noticed that the cluster name in `TestBackupAndRestore` needs to be fixed as well
https://github.com/coreos/etcd-operator/blob/master/test/e2e/backup_test.go#L66

**Comment by hongchaodeng** [comment]
@hasbro17 
Great findings!
The fix makes sense to me.
We also need to wrap the error in PrepareTLS() and print error message from os command.
