### ISSUE TITLE
Client Service "tolerate-unready-endpoints" annotation causes connection issues

### ISSUE THREAD

**Issue by gjcarneiro** [coreos/etcd-operator#2030]
I don't know whether this is just a question, or a bug in etcd-operator, or a bug in kubernetes itself.

In any case, I was just playing with a 3 node etcd cluster and the impact on clients when I delete one of the cluster members.

I use a simple command like `etcdctl get --prefix /` in a loop, while I delete one pod, and wait for a replacement pod to appear.

The problem happens when the new pod appears, it is not yet Ready, but the Service endpoints include the new pod:

```
$ kubectl get ep example-etcd-cluster-client
[...]
example-etcd-cluster-client   10.125.27.21:2379,10.125.6.10:2379,10.126.8.18:2379   41m
```

But at the same time the pod is still initialising:

```
example-etcd-cluster-kbn69vn2xn   0/1     Init:0/1   0          6s    10.125.6.10    hex-48b-pm.k2.gambit   <none>           <none>
```

As a result, my etcdctl gets either delayed for 1 second or so, or gets an error, or works fast, randomly.

As soon as the new pod finishes initialising, the service is restored.

To be honest, to be this seems like a Kubernetes bug -- it shouldn't add a pod to a Service endpoints list before the pod is Ready -- but I could be missing something.  Otherwise, how can you have zero downtime with etcd, with expected node maintenance requiring me to evict pods from nodes, once in a while?

Any thoughts?

**Comment by gjcarneiro** [comment]
Argh... after much googling and even reading kubernetes source code I found the problem:

```
07:42:09 {master} ~/Downloads/etcd-operator$ kubectl --context=dev get svc  example-etcd-cluster-client -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
```

Why is the `tolerate-unready-endpoints` annotation being used, and how can I get rid of it?

**Comment by gjcarneiro** [comment]
So, #1257 says "Set TolerateUnreadyEndpoints for service of peer URLs".

I have no problem with the peer service.  Makes sense to have TolerateUnreadyEndpoints for it.

But the same patch also added TolerateUnreadyEndpoints to the client service.  I think this one was accidental and is harmful.  cc @hongchaodeng.

**Comment by alaypatel07** [comment]
@gjcarneiro I agree, the peer URLs are networked by a headless service and the annotation is used in a similar manner as it would be in a StatefulSet (mentioned in the documentation of `publishNotReadyAddress`).

Each pod checks its own DNS entry before initializing, here: https://github.com/coreos/etcd-operator/blob/aeb3e3e0835ec5135cfe50340f59853b5b6fc407/pkg/util/k8sutil/k8sutil.go#L373

If only the headless service (one which services Peer URLs) is annotated with `publishNotReadyAddresses`:
1. A DNS entry will be populated because of the headless service, and `check-dns` will resolve correctly.
2. The `[cluster-name]-client` endpoint will not be populated with an unready pod IP:port-number, resolving this issue.

Good catch :)
