### ISSUE TITLE
integrating with kubeadm

### ISSUE THREAD

**Issue by errordeveloper** [coreos/etcd-operator#335]
I am exploring how integration with kubeadm could work on top of what we currently have, so we can build a PoC where etcd would be pivoted from single static pod to a cluster.

Let's say we want to enable a use-case where someone builds a cluster with kubeadm and get a single etcd in a static on the master, and at some point later they decide to improve the system and introduce etcd operator (perhaps this could be right after they ran kubeadm, or some number of days later and they have more then basic dataset in etcd).

So for the following to happen, I'd like to learn what is everything I need to do.

Having ran the example out of the box, I've observed that first peer gets started with the following arguments:
```
etcd --data-dir=/var/etcd/data --name=etcd-cluster-0000
      --initial-advertise-peer-urls=http://etcd-cluster-0000:2380 --listen-peer-urls=http://0.0.0.0:2380
      --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://etcd-cluster-0000:2379
      --initial-cluster=etcd-cluster-0000=http://etcd-cluster-0000:2380 --initial-cluster-state=new
      --initial-cluster-token=641d3e0b-ab95-4b62-98fc-ed2d711e4238
```

I would assume that adding address of existing instance to these arguments, set `--initial-cluster-state=existing` and remove `--initial-cluster-token=...`, the data would get replicated into the new cluster.

Next, I'd assume that once I have enough peers, it'd be plausible to update etcd static pod and make it run in proxy mode. Perhaps we get rid of the static pod once Kubernetes API server is also happy, but it shouldn't hurt to keep it around either.

Does this sound about right or am I missing something?

---- 

P.S.: I know static pods are to be replaced by kubelet API, but there must be a simple thing we could do that would be much easier and it would enable many users. We all know what's wrong about static pods, but for the sake of making progress, let's ignore those issues.

cc @philips @justinsb @lukemarsden @jbeda

**Comment by pires** [comment]
AFAIK, this operator assumes the control plane to be in place. What you seem to be looking for is:
* bootstrap initial etcd node (`--initial-cluster-state=new`)
* start control plane
* deploy operator and point it to an existing cluster (`--initial-cluster-state=existing`), meaning you'll be scaling the etcd cluster.
* optionally, after operator finishes bringing the new nodes, terminate initial etcd

There's a [comment thread in a document](https://docs.google.com/document/d/1VNp4CMjPPHevh2_JQGMl-hpz9JSLq3s7HlI87CTjl-8/edit?disco=AAAAAstN0Xs) and [an issue](https://github.com/kubernetes-incubator/bootkube/issues/31) that describe this into more detail.

Also, it's gonna be a while before kubelet pod API has feature parity with static pod manifests - I mean, assuming there will be a kubelet pod API.

**Comment by jbeda** [comment]
The problem here, I think, is that the API server needs a static address for the etcd server that backs it.  (K8s services work via the endpoints API which hits etcd so we can't find etcd through regular k8s services.)  I'm not sure how much value (and how adaptable things are) if we try and use the operator with a relatively static config.

CoreOS folks -- are you using these operators for the etcd backing the cluster in your bootstrap configs?

**Comment by philips** [comment]
The discussion and prototype is at https://github.com/kubernetes-incubator/bootkube/pull/176

**Comment by philips** [comment]
Also @xiang90 is tasked with making the call on how we proceed with this and whether we use host networking or go through a network bootstrap.

**Comment by aaronlevy** [comment]
An option we've discussed is to use a service IP that we pre-allocate to the etcd cluster (similar to what we do with dns addon).

- The bootstrap api-server will contact a "seed" etcd (likely started as static pod) via a static configuration.
- Then the self-hosted api-server will be configured to contact the etcd cluster via the pre-allocated service IP
- When we "pivot" from the bootstrap control plane to the self-hosted replacement, the etcd controller will have already started pods which satisfy the etcd service endpoint, and the self-hosted api-server will be able to contact it via that service.

**Comment by xiang90** [comment]
> I'm not sure how much value (and how adaptable things are) if we try and use the operator with a relatively static config.

Good question.

I am still evaluating the idea of "self-hosted etcd" - managing the Kubernetes's etcd by etcd-operator running atop of Kuberentes. 

The goal is to:
- 1. greatly reduce mean time to recovery for most common cases
- 2. hide the tedious work (backup, upgrading) of operating etcd
- 3. make it easier to setup a self-hosted kubernetes cluster

Hiding etcd completely from k8s human operators is non-goal. They still need to monitor etcd if they run large clusters for example.

The benefits I can see so far are:

- automatic backup (for 2)
- automatic failure recovery for non-disaster case  (no quorum loss. for example, we lose 2 out of 5 etcd nodes)  (for 1, 2)
- automatic rolling upgrade (for 2)
- automatic cluster resizing (for 2, 3)

The problems I can see so far are:

- 1.complicated bootstrap story
  - We need to migrate etcd outside Kubernetes into Kubernetes
- 2.complicated disaster recovery when etcd loses its quorum
  - The operator relies on Kuberentes to schedule etcd pods. The created etcd relies Kubernetes Pod networking + service discovery.


@hongchaodeng, @aaronlevy and me already "solved" 1 ("complicated bootstrap story") by automating the seed member migration in bootkube. (see @aaronlevy's reply). It is still complicated, but it is automated. So I think now it is less a problem.

I am now looking into 2.

There are essentially two sub cases for 2.

2.1  We permanently lose quorum: machine lost. I intent to treat this case a Kubernetes  level master component disaster recovery. Basically we need to go through the initial bootstrap case except that the seed etcd cluster is created from a pervious backup.

2.2 We temporarily lose quorum: machine reboots, power failure. The problem for this case is really just networking since Kuberetes requires a working etcd. And self-hosted etcd cluster relies on Kuberenetes networking. So we need to figure out how to break this cycle. 

Potential solutions:
- 1.checkpoint k8s networking setup for the master components. So the networking can recover even if k8s is not there. 

- 2.use host networking for self-hosted etcd.

1 complicates bootkube. 2 complicates etcd-operator. We are still exploring.

@jbeda @errordeveloper @pires We, at CoreOS, feel the entire self-hosted etcd idea worth to explore based on my reasoning. What do you think? Any potential issue you can see? 

/cc @hongchaodeng @philips @aaronlevy Feel free to add anything that I forgot to cover. Thanks!

**Comment by philips** [comment]
@xiang90 this all makes sense. What do you think are the next steps on figuring out 2.2?

Personally, given the choice between trying to make changes to external components like the API server or networking and adding complexity to the etcd Operator I would rather add complexity to the etcd Operator. For example I don't know how to checkpoint this stuff and still recover if we are defaulting the API server to quorum reads. 

Lets talk on Monday because I would like to have this sorted out in the next few weeks and I haven't given it as much thought as you have.

**Comment by xiang90** [comment]
> Personally, given the choice between trying to make changes to external components like the API server or networking and adding complexity to the etcd Operator I would rather add complexity to the etcd Operator.

I feel so. I had some discussion with @aaronlevy. And I feel there could be too many uncertainties  "oops" if we try checkpoint approach. 

There will be uncertainties for adding support at etcd operator side too. And it will require significant effort. But I think we can somehow manage it if:

1. only support one self-hosted etcd cluster per operator (or even per Kubernetes cluster)
2. only support hosted networking for the self-hosted etcd cluster
3. separate the bootstrap and member add code path for self-hosted and normal etcd cluster management initially
4. continuously integrate and test with bootkube
5. accept potential constraints (say we can only recover the cluster in most of the cases, but not 100%.) in short term

I am happy to talk through this net week and get the initial implementation done as long as @hongchaodeng and @aaronlevy also happy with this approach.

**Comment by pires** [comment]
> 5. accept potential constraints (say we can only recover the cluster in most of the cases, but not 100%.) in short term

This, the disaster recovery, is my only concern. Other than this, everything else can be either fixed or worked-around by the smart people involved in this.

**Comment by xiang90** [comment]
> the disaster recovery

Personally, I feel this would be a documentation issue initially. Totally hiding etcd from the kuberentes operators is a non-goal for now. Human operators still need to have basic etcd knowledge to recover it from extreme failure cases, although the goal is to reduce the number/possibilities of these cases. We need to learn from the operational experience to understand what happens frequently and what is not. So we can make trade-off more smarter in the future.

**Comment by pires** [comment]
Making this dumb proof has never been a goal of mine, so I agree.

**Comment by pires** [comment]
@xiang90 is the next step to actually run the etcd operator after the cluster is up?

**Comment by pires** [comment]
Nevermind, https://github.com/kubernetes-incubator/bootkube/blob/9ffd0b68a906a4450c482b83ec3aa6057bee22c1/pkg/asset/k8s.go#L34.

**Comment by xiang90** [comment]
@pires 

Bootstrap phase is integrated with bootkube with a feature flag. Check bootkube repo for more detail on that.

The next step is to handle non failure recovery case. It does not necessarily have anything to do with etcd operator. It requires some change in bootkube itself. We are working on it.

The next next step is to handle backup/recovery from backup for disaster case.

**Comment by pires** [comment]
@xiang90 correct. I was just looking for how you were doing HA self-hosted. I totally understand the backup/recovery is not yet part of this solution.

**Comment by xiang90** [comment]
I am closing this. We should move the talk to bootkube. Most of the self-hosted required features from etcd-operator side are done.
