### ISSUE TITLE
x509: provide static secrets to an EtcdCluster

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#409]
It would be nice to enable a user to generate static x509 certificates and keys, put them into Kubernetes, and then specify their use via the EtcdCluster resource.

The basic configuration would be the addition of four fields to the resource:

- client-cert
- client-key
- member-cert
- member-key

The workflows and docs that need to be considered before this is completed:

- [ ] Basic self-signed setup
- [ ] Basic offline self-signed CA and online intermediate
- [ ] Key and certificate rotation

**Comment by hongchaodeng** [comment]
Hi @philips 
Can you clarify more detailedly on these two points:

> - Basic self-signed setup
> - Basic offline self-signed CA and online intermediate

**Comment by philips** [comment]
Essentially we need to provide a doc that shows a user how to run the various openssl commands, load those certs into secrets, and then run a cluster. 

We need the etcd-operator equivalent of these docs:

https://github.com/coreos/docs/blob/master/os/generate-self-signed-certificates.md 
https://coreos.com/etcd/docs/latest/op-guide/security.html

**Comment by hongchaodeng** [comment]
Hi @philips 

> Key and certificate rotation

Any reference/docs for doing cert rotation?

**Comment by philips** [comment]
Essentially if you need to move from cert-old to cert-new how does that work? Do I take downtime? Where do I put cert-new? How do I tell the cluster to move from cert-old to cert-new?

**Comment by hongchaodeng** [comment]
ref spec PR: https://github.com/coreos/etcd-operator/pull/899

**Comment by hongchaodeng** [comment]
Here's an update on the plan for this issue.

First of all, we have defined spec in https://github.com/coreos/etcd-operator/pull/899 for how to give operator certs/keys and deploy TLS cluster.

But the question continues on how to generate certs for etcd pods. A few points:
- etcd client will check its endpoints against server certficate's Subject Alternative Name (SAN).
- etcd pods' names are dynamically assigned. For example, I could have etcd-0, etcd-1, etcd-2; but if etcd-2 dies, we would replace it with etcd-3. As a result, we need to wildcard hostnames. An example: https://github.com/coreos/etcd-operator/issues/901#issuecomment-290891943 .
- For client connection, the "wildcard" method needs to be applied to creating server certificate.
- For peer connection, it is different for normal and self-hosted case.
  - For normal case, we can use the same "wildcard" method to create peer certificate. 
  - For self-hosted case, we don't use service names for peer urls (this is due to hostNetwork couldn't use DNS). Thus, we can't make assumptions on what to "wildcard" and even "wildcard". For example, users might choose to set IP in SAN and then it must be exact match.

**Comment by hongchaodeng** [comment]
This is done.
Docs is provided in https://github.com/coreos/etcd-operator/blob/master/doc/user/cluster_tls.md .
We will extend the docs and provide some example including certs later.
